### ISSUE TITLE
[QUESTION] Overlay Style Editing

### ISSUE THREAD

**Issue by MillsV2** [FaeyUmbrea/obs-utils#104]
This might also double as a request to edit the documentation of the module, but how does one use the style editing in the overlay editor? 
I'm not sure if there's a specific type of code or what not to edit it, and I'd appreciate any documentation/clarification on how to use that field

**Comment by FaeyUmbrea** [comment]
Right now all it does is take whatever you put into the field and set it as an inline style attribute on the component. 
So you need to paste inline CSS into that field.
Down the line I want to make a proper style editor, but that will take a bit of time.

**Comment by FaeyUmbrea** [comment]
I've added a blurb to the Docs.
