### ISSUE TITLE
[BUG] No /stream transparent background

### ISSUE THREAD

**Issue by 9ryex5** [FaeyUmbrea/obs-utils#112]
I'm currently using OBS Utils 1.4.0. When I access /stream through a browser, the background is transparent.
However when I do it through OBS, it's the default bright green.

Did I jump some step or is this a bug?

**Comment by FaeyUmbrea** [comment]
Uh that is not quite what should happen..
Do you have any custom CSS settings applied in OBS?
If not, you might have to check if there is any errors that appears in the OBS browser source. 
You can do that by following the steps outlined here: https://obsproject.com/forum/threads/how-to-get-console-log-in-browsersource.110221/

**Comment by FaeyUmbrea** [comment]
Also OBS Version might matter, which one are you on?

**Comment by 9ryex5** [comment]
I had the default custom CSS in OBS `body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }` on my /stream source, just removed it but nothing changed.
OBS version 29.0.0 (64 bit) which is the latest.

I don't think there are any errors 
![image](https://user-images.githubusercontent.com/43207603/214386842-3a1f2501-4a5f-421d-a385-13a6136f2fc6.png)

**Comment by FaeyUmbrea** [comment]
Huh... this is strange. Can you show me the style breakdown for the body element? (the one that is already selected in that screenshot)
It's the one that would be at the very bottom of that screenshot. 
I'd like to know specifically where it's getting it's background-color property from.

**Comment by 9ryex5** [comment]
![image](https://user-images.githubusercontent.com/43207603/214453683-da5be2fe-b5be-4a88-ab51-2f2843933654.png)

**Comment by FaeyUmbrea** [comment]
For some reason the module stylesheet is not loading for you in OBS. 
I unfortunately can't reproduce the behaviour on my end at all. 

The debug tools also have a network view. You might be able to use that to see if the stylesheet is simply not loading for some reason. 

Are you hosting foundry locally, on a remote server or are you using a service like the forge?

**Comment by 9ryex5** [comment]
Apparently it had to do with Cache, refreshing it on the chat source fixed the problem. Thanks for the help anyway :)
![image](https://user-images.githubusercontent.com/43207603/214839157-a74b5d90-005d-4c36-8d21-15d9fa6d961e.png)
