### ISSUE TITLE
Multiple Sources linked to the same page generate problems

### ISSUE THREAD

**Issue by ZeroIchiro** [FaeyUmbrea/obs-utils#114]
Hi, 
don't know if that's a general Problem with FVTT, but I hoped your plugin could fix a nasty Problem we face.
So, we're streaming our sessions on Twitch, and our group consists of 8 players + 1 GM, so in total, we have 9 different Browser Sources just for displaying the rolls on stream.
The Problem is that for some reason, when I login with the Overlay Account, it gets 3, max 4 of the roll-sources running, the others have to "re-login".
Also, whenever I login, I get redirected to the game view, even though I entered the /stream address in OBS browser source.
So... am I just to stupid to setup your plugin properly, am I reaching some FVTT limitations, or is there something else wrong, maybe with my FVTT Server. I run FVTT on a virtual Debian Server reachable from the entire internet.

Thank you in advance
Kind Regards
Zero

**Comment by FaeyUmbrea** [comment]
Hold up what rolls are you displaying that you need 9 Browser Sources?

Also the login always redirecting to /game is unfortunately a Foundry issue, nothing to be done about that until FVTT changes that

**Comment by ZeroIchiro** [comment]
Well, look at our overlay:

![grafik](https://user-images.githubusercontent.com/51971338/228070161-7aba3da3-49c6-4f6e-8403-dd954524b3cc.png)

every round icon with a d20 in it is displaying the respective player's last roll constantly. Which means, together with Stream Utils, we open 9 browser sources and crop them accordingly. We haven't found a different solution for that yet. We dabbled with parsing these information via Powershell, but it didn't work out.

**Comment by FaeyUmbrea** [comment]
Oh wow!
Stream Utils' a different module though, I am not even sure if my module supports displaying roll results at the moment as all mine can display is actor values.

I do have a roll display on my ToDo-List though.

Can you get the roll results to all display on the same /stream source? If so, you can duplicate the source and crop it differently each time instead of using 9 different browser sources

**Comment by FaeyUmbrea** [comment]
Ah I see

I started developing this module a while ago during a time when Stream Utils seemed abandoned. I can give you a ping on this issue once I had time to get around to adding roll overlays. Got that feature request a couple of times now

**Comment by FaeyUmbrea** [comment]
Added a roll display overlay, closing this now
