### ISSUE TITLE
Add webcam layer

### ISSUE THREAD

**Issue by HonzoNebro** [FaeyUmbrea/obs-utils#116]
I'd love for it to be an option to show the webcam layer, that's all I need for a perfect streaming experience, right now having to resort to Discord + crop wastes a lot of screen, since I only use one it's a bad experience.

**Comment by FaeyUmbrea** [comment]
Hi there, I don't have a lot of experience using the builtin webcams of FoundryVTT. 
Do you know if they show up on /stream by default? I'm hiding them on /game right now but I could implement a toggle to allow them to show up there. However I think having them available on /stream might actually be better because that way the can be positioned separately from the canvas.

**Comment by HonzoNebro** [comment]
They do not show on /stream by default.

I guess having the option for them to show on either /game or /stream would be ideal. I worry though if that would break compatibility with plugins like LiveKit or Falemos

**Comment by FaeyUmbrea** [comment]
Hmm from the looks of it Falemos seems to be cooking its own thing. LiveKit actually uses the recommended builtin of changing the WebRTC implementation. 

I think I'd have two routes here: 

1.  Implement a simple setting that just toggles if the AV part of the UI is hidden on /game or not. 
2. Try and see if I can get the AV Application to somehow show up on /stream which would most likely be incompatible with Falemos.

**Comment by FaeyUmbrea** [comment]
Also, there is unfortunately no way of getting the camera streams through discord. So it'll have to be either the builtin AV or it won't be available.

Let me know if you'd be happy with option 1, I'm not sure if option 2 is possible but I can try to figure it out. Might take a while though.

**Comment by HonzoNebro** [comment]
I'm more than happy with option 1, that was my plan anyways, but I can see the appeal in option 2

**Comment by FaeyUmbrea** [comment]
Hi there. 
I've added a setting to the latest release. 

Option 2 would be a lot of work because the webrtc module is not initialized in /stream mode. So I'd have to init it manually to make this work. I'll postpone this to much later, or until someone specifically requests it

**Comment by HonzoNebro** [comment]
Thanks a lot! I'll consider this issue closed.
