### ISSUE TITLE
https requires websocket over wss

### ISSUE THREAD

**Issue by WilliamSmith999** [FaeyUmbrea/obs-utils#119]
Hello, I can't see to find anything on enabling WSS to use this pulgin. Is there any plan to add WSS?

Error: Mixed Content: The page at '\<siteaddress\>/game' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://\<address\>:\<port\>/'. This request has been blocked; this endpoint must be available over WSS.

**Comment by FaeyUmbrea** [comment]
I can't add WSS support as I'm not the one who provides the websocket. The websocket is provided by OBS Studio. You should not see this error from my module at all because the embedded browser within OBS should accept mixed content connections to localhost no problem.

**Comment by WilliamSmith999** [comment]
I see. To clarify I am not running the server on the localhost it's a separate server I manage. I'll have to investigate from the obs side then, thank you.

**Comment by FaeyUmbrea** [comment]
Just for further clarification: The URL/IP you are entering into the websocket configuration is for the OBS Studio instance running the webserver. Since the module is intended to run inside a browser source, localhost should be sufficient for most users.

**Comment by WilliamSmith999** [comment]
Machine A is running OBS studio, Machine B is running my foundryVTT instance. The plug in is configured with Machine A's ip.

**Comment by FaeyUmbrea** [comment]
The OBS Websocket is accessed from the browser source client instance. Not the server. Foundry Modules have no way of modifying server code.

**Comment by FaeyUmbrea** [comment]
Closing this issue as stale
