### ISSUE TITLE
This is almost perfect but I need the chat

### ISSUE THREAD

**Issue by TheAlexPlus** [FaeyUmbrea/obs-utils#122]
Maybe I'm missing something, but I'd like to be able to include the chat in my stream, but now that im logged in to the user, i can't do it with monks common display anymore.

**Comment by TheAlexPlus** [comment]
I had tried that, but it doesn't show anything on it.  It just gives me a green screen.

**Comment by FaeyUmbrea** [comment]
That is very odd. The chat should display all messages the account has access to and the background should be transparent if use inside an OBS browser source is detected.
Are you using the Forge/Hosting or are you running Foundry on your own PC?

**Comment by TheAlexPlus** [comment]
From an amazon server.
The first overlay comes up great, but if i add the /stream one, it's all green with no chat.
I'm going to try it again real quick, but I'm not sure what's going on.

Also, will i need to interact and log in as the appropriate user every time?  It's not that big of a deal if so, I'm just not sure how to set up the login stuff in the settings

**Comment by FaeyUmbrea** [comment]
Ah yes, unfortunately that is a limitation of foundry. You can limit the amount of log-ins to once per stream by doing the workaround I described above. Hide all sources except one (I use the game view here) and then, after logging in, showing all the other sources (like chat) with the option that the source is disabled if not visible.

That will make all of them log into the same account.

Oh just for your information, you should have a message readable by the stream user in the chat, it doesn't have a background on /stream

**Comment by TheAlexPlus** [comment]
ok, well.. I tried it again and it was just green, but after like 2 minutes, the chat popped up... but everything is still green.  I was able to easily key it out though

**Comment by FaeyUmbrea** [comment]
That's odd... the background should be set to transparent by the plugin.
What version of OBS are you using? And what OS are you on? It might be that the browser source is behaving erratically on certain versions or systems, if so I have to revise my detection code...

**Comment by TheAlexPlus** [comment]
It could very well be that my OBS is behind.  I'm running 28.1.2  and I'm on Windows 10

**Comment by FaeyUmbrea** [comment]
Hmm that should be fine, but you could try upgrading to 29.1.3 which is what I am on, if your plugins allow...

Just to make sure, you are using a "Browser Source" not a "Window Capture" correct?

**Comment by FaeyUmbrea** [comment]
Closing as stale
