### ISSUE TITLE
Overlay Templates

### ISSUE THREAD

**Issue by igorteuri** [FaeyUmbrea/obs-utils#127]
Hello! Great module!

Is there any CSS Overlay Templates? I don't know much about CSS, thus I couldn't create some overlays to show up on /stream. It would be awesome to have some as reference to begin with.

**Comment by FaeyUmbrea** [comment]
Hi there, unfortunatley there is no CSS templates at the moment. I don't quite understand the second part of your comment though. The overlays should still render even without any CSS applied to them. What were you trying to make exactly?

**Comment by Somel1978** [comment]
> Hi there, unfortunatley there is no CSS templates at the moment. I don't quite understand the second part of your comment though. The overlays should still render even without any CSS applied to them. What were you trying to make exactly?

I believe he was trying to achieve what I'm trying to achieve. Is for example create an overlay for an actor so he can have that actor live data on the stream. For example for Avtor A on a dnd campaign the overlay would show the stats, the HP  and the AC.

I could not find a way yet, but my gut tell me that this is easily achievable, after all is just a print of actor fields into an overlay.

**Comment by FaeyUmbrea** [comment]
I don't currently use this feature of the module much, but you can find a really good template, or contribute your own, on the new discord server I made!
