### ISSUE TITLE
[Suggestion] Ability to set the pop up size and position

### ISSUE THREAD

**Issue by igorteuri** [FaeyUmbrea/obs-utils#128]
I loved the module, and I plan to use it on my streams. But there's an option in Stream View that allows me to set pop up size and position.  This is very useful, since this way we can certify that none of the pop ups will be cut off on stream. 

Thanks for your amazing work.

**Comment by FaeyUmbrea** [comment]
Hi there! I'm glad you enjoy my module. 

Can you give me a bit more information about the behaviour you are looking for? 
Is it a global setting? Does it limit the size, shrinking the elements that are too big or does it set the size, shrinking and growing all elements to the defined size?

**Comment by FaeyUmbrea** [comment]
A screenshot would also be helpful if you can provide one.

**Comment by igorteuri** [comment]
Hello! Thanks for answering. 

Here's a screenshot of the Stream View feature I'm talking about. 
![image](https://github.com/FaeyUmbrea/obs-utils/assets/64547748/53e80648-d321-4705-a589-ceacc3a8a9c4)

It is not a global setting, it works only for the Livestream user. In Stream View module you estblish a player as the Stream User. All settings only works for this user. Obs Utils does this automatically by dettecting the Browser Source, so the feature would need to detect that as well, I suppose. You set the desired size and it shrink or grow the popout to it. It allows the streamer to pay attention in the game itself, because they don`t need to check everytime if the poupout is being cut by the overlay. 

This is an overlay I made for my stream with a popout setted in this way with Stream View. 
![image](https://github.com/FaeyUmbrea/obs-utils/assets/64547748/06df7974-6403-4a1e-8a97-dc643cd04b8e)

**Comment by FaeyUmbrea** [comment]
The latest update contains this feature now. No support for negative numbers as that does not seem very frequently used.

**Comment by igorteuri** [comment]
> The latest update contains this feature now. No support for negative numbers as that does not seem very frequently used.

Thanks a lot for your amazing work!
