### ISSUE TITLE
Can't figure out overlays

### ISSUE THREAD

**Issue by Jasper-J-R** [FaeyUmbrea/obs-utils#135]
Hi, I'm trying to get the roll and actor overlays to work, however if I set something in the overlay editor, nothing appears.

Here is my overlay editor: 
![image](https://github.com/FaeyUmbrea/obs-utils/assets/153030170/3b07ebdc-701c-4a45-aced-dc45becba6d8)

Here is my stream in obs: 
![image](https://github.com/FaeyUmbrea/obs-utils/assets/153030170/4328ccf5-ed0c-402b-8ac8-4bd5aca5282e)

I don't see an overlay, and I can't find a way to make it appear. Any help would be appreciated.

**Comment by FaeyUmbrea** [comment]
Ah, the overlays are on a different URL from the main game view. Copy the URL you are using and make a new Browser source. Instead of /game point it at /stream.

You can find some more pointers here: https://github.com/FaeyUmbrea/obs-utils/wiki#setting-up-obs

**Comment by Jasper-J-R** [comment]
Ah that did it thank you.
