### ISSUE TITLE
Roll Overlay Size

### ISSUE THREAD

**Issue by Jasper-J-R** [FaeyUmbrea/obs-utils#136]
Hi, the roll overlay number seems quite small by default, is there a way to make it larger?

**Comment by FaeyUmbrea** [comment]
The overlays are generated with some default CSS in place, or you can use the editor directly to add in-line CSS arguments that are rendered in the components style tag. 
https://github.com/FaeyUmbrea/obs-utils/wiki/Stream-Overlay-CSS

**Comment by Jasper-J-R** [comment]
I don't believe there is a way to use the editor to adjust the roll overlay element based on what I saw, only the other overlays. I should be able to adjust it with custom css though, so I will do that.
