### ISSUE TITLE
[Feature Request] Event of Foundry Scene Activate

### ISSUE THREAD

**Issue by TehStoneMan** [FaeyUmbrea/obs-utils#137]
Can it be possible to add an event when activating or deactivating a Foundry VTT scene? This would allow, for example, having a player focused OBS scene when on a non-map Foundry scene, such as a theatre-of-the-mind set-up, or pre- or post-game period, and then automatically switch to a map focused OBS scene when activating a battle map Foundry scene.
This may require having the ability to filter the event based on which Foundry scene is being activated.

**Comment by FaeyUmbrea** [comment]
Alright, I have added a Foundry Scene event to the OBS Remote.
The Scene Load gets filtered by Scene name. For ease of use, you can just drag and drop a Scene into the textbox.
When setting up, please keep in mind that the events for that scene will also trigger when foundry loads that scene on startup, so if you use toggles, make sure they won't break your stream setup if the browsersource reloads.

I'll leave this open in case you want adjustments to the Feature!
