### ISSUE TITLE
Dice so Nice rolls appear brown

### ISSUE THREAD

**Issue by Kaallis** [FaeyUmbrea/obs-utils#139]
When I roll dice with dice so nice, the dices appear brown and the numbers can't be seen well.
In foundry, they are colorful.

**Comment by FaeyUmbrea** [comment]
I am unsure what my module has to do with that, I don't touch any of the stuff that dice so nice does

**Comment by Kaallis** [comment]
In Dice so nice, performance, turn off realistic dice. That fixed it. Gotta make sure it's done for the user logged in in OBS.
