### ISSUE TITLE
V12 update?

### ISSUE THREAD

**Issue by norbit58** [FaeyUmbrea/obs-utils#142]
![chromium error](https://github.com/FaeyUmbrea/obs-utils/assets/124216509/8e79aadf-9b5c-4f70-85ef-4076fbd47c5b)
I am getting this error with the recent update. I can see the game, but no lights or tokens. Will there be a fix for this? Much appreciated and sorry for the trouble.

**Comment by FaeyUmbrea** [comment]
Hello. This is not a module error. As the error message clearly states, this is because the chromium version in OBS is lower than the minimum required version to run Foundry V12.

**Comment by FaeyUmbrea** [comment]
After investigating, I have concluded that foundry and the module work perfectly fine in OBS. I am unsure what is causing your issue but it is not OBS or OBS-Utils.
