### ISSUE TITLE
Missing Director options in V11

### ISSUE THREAD

**Issue by halfd0rk** [FaeyUmbrea/obs-utils#143]
With the new update OBS-utils is not showing up as an icon nor in the game settings inside V11. 
![chrome_am4s2Fuff8](https://github.com/FaeyUmbrea/obs-utils/assets/84686949/abb9cd9d-5a46-4acb-9d82-2b607b52edb9)

**Comment by FaeyUmbrea** [comment]
That is rather odd... it's definitely showing up for me locally, regardless of browser. I don't have a forge account so I can't check anything on there..

Do you have any browser console errors that have obs-utils in the name if you press F12?

**Comment by FaeyUmbrea** [comment]
I'm actually going to reopen this. There was a race condition that would sometimes mean the code creating the UI Buttons would execute too late.
