### ISSUE TITLE
Tagger dependency is discontinued and it produces bugs on V12

### ISSUE THREAD

**Issue by HonzoNebro** [FaeyUmbrea/obs-utils#144]
I finally switched to V12.327 and tagger is giving me problems with things such as editing scenes, the window doesn't close and I have to reload the page.

I've tested this by only enabling tagger on a pf2 world.

Since that module hasn't updated since june 2023, it may have been abandoned, is it possible to stop depending on it?

**Comment by FaeyUmbrea** [comment]
Hi there! Thank you for pointing this out. I have taken the time to fully remove tagger and socketlib from the dependencies. 
This will mean that all existing tokens have to be re-tagged.
