### ISSUE TITLE
Save Window to Stream

### ISSUE THREAD

**Issue by Kharmans** [FaeyUmbrea/obs-utils#147]
I notice that when a NPC is prompt to roll a save, the save only show on the OBS User. That's really bad cause that user is the user to stream. Can be fixed?

**Foundry**: v12.328
**D&D5e**: v3.2.1

**Comment by FaeyUmbrea** [comment]
This bug has nothing to do with my module. I don’t have any code that would prevent a different user from getting a save prompt
