### ISSUE TITLE
Prevent the user configuration pop-up from popping

### ISSUE THREAD

**Issue by liquidsonic** [FaeyUmbrea/obs-utils#150]
Right now unless I have a user assigned I get the user config from popping up

![image](https://github.com/user-attachments/assets/06407b78-9fca-432a-815f-42d09a9074ed)

For reasons of some module mixing I'd rather OBS Util potentially lock this down as an option as it makes sense that maybe you don't want an Owner/observer about

**Comment by FaeyUmbrea** [comment]
That's foundry core behavior introduced in v12, I could make an option to hide this UI element in OBS, but you could just as easily make a dummy actor and assign it as the player character for your stream user. I am unsure why they introduced it.

**Comment by liquidsonic** [comment]
I know, I ask because of a setup I have implemented which is using Party
HUD and letting it show through OBS Util. However that pop-up keeps
appearing everytime I start the stream, reload the game etc. :/

Its not a big deal if its trouble, I thought I'd ask since I imagine it's
something that would affect people's general usages anyways
