### ISSUE TITLE
Chat Permission

### ISSUE THREAD

**Issue by Kharmans** [FaeyUmbrea/obs-utils#153]
It's possible to create an option where you can choose to show the chat with player permissions and not GM? Since the stream user has to be a GM too, it streams a lot of information on chat that it's for GM only ad it's not good to go to stream.

**Comment by FaeyUmbrea** [comment]
What do you mean? The stream user does not have to be a gm

**Comment by Kharmans** [comment]
Oh, my bad, I remember reading that the stream user has to be a GM.

**Comment by FaeyUmbrea** [comment]
I think that might have been another module... at least I hope so, otherwise I have wrong data somewhere in my docs

I'll close this
