### ISSUE TITLE
Problems with the field of vision 

### ISSUE THREAD

**Issue by CaptainKalli** [FaeyUmbrea/obs-utils#155]
Hey in OBS I have everything displayed via a player ‘stream’. This should show the DM's view. However, when I zoom into Foundry, the player's view shifts and no longer shows the correct view.

**Comment by FaeyUmbrea** [comment]
Sorry, but I can't reproduce this issue as described.
Please keep in mind that the OBS view and the browser view might have different resolutions, which can cause some drift between what you see and what the stream sees.
