### ISSUE TITLE
Erro When Update

### ISSUE THREAD

**Issue by Kharmans** [FaeyUmbrea/obs-utils#163]
This error is showed when trying to update.

![image](https://github.com/user-attachments/assets/2fc7229a-b608-40fd-ab9c-9741519771f5)

**Comment by FaeyUmbrea** [comment]
Should be fine now (this is foundry core though, so I don't know whats wrong exactly, I think its a module.json formatting mistake)

**Comment by Kharmans** [comment]
Worked! Thanks!
