### ISSUE TITLE
[FEATURE] Tracking of PC Tokens

### ISSUE THREAD

**Issue by Kharmans** [FaeyUmbrea/obs-utils#169]
In the Director Window, is possible to track all controlled tokens, but that includes NPCs. It would be possible to have an option to track only PC tokens?

**Comment by FaeyUmbrea** [comment]
You can track an arbitrary list of tokens by right-clicking them and clicking the little stream icon on the bottom right of the token menu. If you generally don't want to track NPCs, you can configure the permission of the stream user to only include player tokens and use the manual tracking mode if you do want to track an NPC, or use it the other way around.

**Comment by FaeyUmbrea** [comment]
This has been implemented
